<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><groupId>com.smartsca.fixtures</groupId><artifactId>maven-profiles</artifactId><version>1.0.0</version><packaging>jar</packaging><name>maven-profiles</name><properties><maven.compiler.release>21</maven.compiler.release></properties><profiles><profile><id>extra</id><dependencies><dependency><groupId>commons-codec</groupId><artifactId>commons-codec</artifactId><version>1.16.1</version></dependency></dependencies></profile></profiles><dependencies><dependency><groupId>org.apache.commons</groupId><artifactId>commons-lang3</artifactId><version>3.14.0</version></dependency></dependencies></project>
