<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>com.smartsca.fixtures</groupId><artifactId>maven-multimodule</artifactId><version>1.0.0</version></parent><groupId>com.smartsca.fixtures</groupId><artifactId>lib</artifactId><version>1.0.0</version><packaging>jar</packaging><name>maven-multimodule/lib</name><properties><maven.compiler.release>21</maven.compiler.release></properties><dependencies><dependency><groupId>org.apache.commons</groupId><artifactId>commons-lang3</artifactId><version>3.14.0</version></dependency></dependencies></project>
