import { test, expect } from '@playwright/test';

test('registers a real request, recovers it after reload and handles an unknown identifier', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByLabel('Proyecto Maven')).toHaveValue('maven-basic');
  await expect(page.getByText('catalog:maven-basic', { exact: true })).toBeVisible();
  await expect(page.getByText(/^fixture-sha256:[a-f0-9]{64}$/)).toBeVisible();
  await page.getByRole('checkbox', { name: 'compile', exact: true }).uncheck();
  await page.getByRole('checkbox', { name: 'runtime', exact: true }).uncheck();
  await page.getByRole('button', { name: 'Registrar análisis' }).click();
  await expect(page.getByRole('alert')).toContainText('Selecciona al menos un scope');
  await page.getByRole('checkbox', { name: 'test', exact: true }).check();
  await page.getByLabel('Contexto de despliegue declarado (opcional)').fill('Laboratorio de calidad');
  await page.getByRole('button', { name: 'Registrar análisis' }).click();
  await expect(page).toHaveURL(/#analysis\/[a-f0-9-]{36}$/);
  const url = page.url();
  await expect(page.getByRole('status')).toHaveText(/EN_COLA|EN_EJECUCION|PARCIAL/);
  await expect(page.getByText('Laboratorio de calidad', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page).toHaveURL(url);
  await expect(page.getByRole('status')).toHaveText(/EN_COLA|EN_EJECUCION|PARCIAL/);
  await expect(page.getByText('Laboratorio de calidad', { exact: true })).toBeVisible();
  await page.goto('/#analysis/00000000-0000-0000-0000-000000000000');
  await expect(page.getByRole('alert')).toHaveText('El análisis no existe.');
  await page.getByRole('link', { name: 'Registrar otro análisis' }).click();
  await expect(page.getByRole('heading', { name: 'Nuevo análisis' })).toBeVisible();
});

test('resolves Maven and filters the persisted inventory by module and direct/transitive context', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('Proyecto Maven').selectOption('maven-multimodule');
  await expect(page.getByText('catalog:maven-multimodule', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Registrar análisis' }).click();
  await expect(page.getByRole('status')).toHaveText('PARCIAL', { timeout: 120_000 });
  await expect(page.getByText('INVENTARIO_Y_EVIDENCIAS_DISPONIBLES', { exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Consultar inventario de componentes' }).click();
  await expect(page.getByRole('heading', { name: 'Inventario de componentes' })).toBeVisible();
  const inventoryRows = page.getByRole('table', { name: 'Identidades y contextos de las dependencias resueltas', exact: true }).locator(':scope > tbody > tr');
  await page.getByLabel('Buscar componente').fill('commons-lang3');
  await expect(inventoryRows).toHaveCount(1);
  await expect(inventoryRows).toContainText('3.14.0');
  await expect(inventoryRows).toContainText('lib · compile · Directa');
  await expect(inventoryRows).toContainText('app · compile · Transitiva');
  await page.getByLabel('Filtrar por scope').selectOption('runtime');
  await expect(inventoryRows).toHaveCount(0);
  await page.getByLabel('Filtrar por scope').selectOption('compile');
  await expect(inventoryRows).toHaveCount(1);
  await expect(inventoryRows).toContainText('lib · compile · Directa');
  await expect(inventoryRows).toContainText('app · compile · Transitiva');
  await page.getByLabel('Filtrar por scope').selectOption('');
  await page.getByLabel('Filtrar por módulo').selectOption('app');
  await page.getByLabel('Filtrar por condición').selectOption('true');
  await expect(inventoryRows).toHaveCount(0);
  await page.getByLabel('Filtrar por condición').selectOption('false');
  await expect(inventoryRows).toHaveCount(1);
  const url = page.url();
  await page.reload();
  await expect(page).toHaveURL(url);
  await expect(inventoryRows).toHaveCount(3);
  await page.getByRole('link', { name: 'Ver grafo y rutas de org.apache.commons:commons-lang3', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Grafo de dependencias' })).toBeVisible();
  await expect(page.getByText('3 rutas en esta página.', { exact: true })).toBeVisible();
  await expect(page.locator('.routes > li')).toHaveCount(3);
  await expect(page.locator('.routes > li').first()).toContainText('Módulo app');
  await expect(page.locator('.routes > li').last()).toContainText('Módulo lib');
  await page.getByLabel('Módulo de las rutas').selectOption('lib');
  await expect(page.locator('.routes > li')).toHaveCount(1);
  await expect(page.locator('.routes > li')).toContainText('Módulo lib');
});

test('shows both Maven diamond routes, supports keyboard selection and recovers the saved graph after reload', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('Proyecto Maven').selectOption('maven-diamond');
  await page.getByRole('button', { name: 'Registrar análisis' }).click();
  await expect(page.getByRole('status')).toHaveText('PARCIAL', { timeout: 120_000 });
  await page.getByRole('link', { name: 'Explorar grafo y rutas', exact: true }).click();
  await page.getByLabel('Buscar en el grafo').fill('commons-lang3');
  await page.getByLabel('Seleccionar componente').selectOption('pkg:maven/org.apache.commons/commons-lang3@3.14.0');
  await expect(page.locator('.routes > li')).toHaveCount(3);
  await expect(page.locator('.routes')).toContainText('commons-configuration2');
  await expect(page.locator('.routes')).toContainText('commons-text');
  await expect(page.getByRole('img', { name: /Relaciones inmediatas.*commons-lang3/ })).toBeVisible();
  const parent = page.getByRole('button', { name: 'org.apache.commons:commons-text @ 1.12.0', exact: true });
  await parent.focus();
  await page.keyboard.press('Enter');
  await expect(page.getByLabel('Seleccionar componente')).toHaveValue('pkg:maven/org.apache.commons/commons-text@1.12.0');
  await page.getByRole('button', { name: 'Ir a la raíz del módulo' }).click();
  await expect(page.locator('.routes > li')).toHaveCount(1);
  await expect(page.getByText('El componente seleccionado es la raíz de este módulo.')).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Grafo de dependencias' })).toBeVisible();
  await expect(page.locator('tbody tr')).toHaveCount(2);
  await page.goto('/#analysis/00000000-0000-0000-0000-000000000000/graph');
  await expect(page.getByRole('alert')).toHaveText('El análisis no existe.');
});
